#!/bin/bash

mkdir ./raw-data
wget -q -P raw-data https://physionet.org/static/published-projects/eegmmidb/eeg-motor-movementimagery-dataset-1.0.0.zip
unzip raw-data/eeg-motor-movementimagery-dataset-1.0.0.zip -d raw-data/eeg-motor-movementimagery-dataset/
