#!/bin/bash

export RAW_DATA=/home/$NB_USER/tutorials/raw_data/

mkdir $RAW_DATA
wget -P $RAW_DATA/ https://physionet.org/static/published-projects/eegmmidb/eeg-motor-movementimagery-dataset-1.0.0.zip
unzip $RAW_DATA/eeg-motor-movementimagery-dataset-1.0.0.zip -d $RAW_DATA/eeg-motor-movementimagery-dataset/
rm -v $RAW_DATA/eeg-motor-movementimagery-dataset-1.0.0.zip
