#!/bin/bash

# Fetch EEG data
export RAW_DATA=/home/$NB_USER/tutorials/raw_data/

mkdir $RAW_DATA
wget -q -P $RAW_DATA/ https://physionet.org/static/published-projects/eegmmidb/eeg-motor-movementimagery-dataset-1.0.0.zip
unzip $RAW_DATA/eeg-motor-movementimagery-dataset-1.0.0.zip -d $RAW_DATA/eeg-motor-movementimagery-dataset/
rm -v $RAW_DATA/eeg-motor-movementimagery-dataset-1.0.0.zip

# Fetch fMRI time series
mkdir /opt/Temp/
cd /opt/Temp/
git clone https://github.com/ramp-kits/autism.git
cd autism/data/fmri/
wget -c wget https://zenodo.org/record/3625740/files/msdl.zip
unzip msdl.zip
